### ISSUE TITLE
Load balancing using multiple mirrors

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie#17]
Gophie API instance on Heroku keeps crashing, the API is public and a lot of people seem to be accessing it, I know Beetubebot is using it, as well as the React platform and the Native platform I am building. If there is any way we can set up to autodeploy to multiple mirrors and have people use the different mirrors instead of concentrating on just one mirror. Look at this for instance https://github.com/dmytrostriletskyi/heroku-load-balancer
Something like that should do the trick right, Spotlight docs can specify multiple mirrors for an endpoint

**Comment by MeNsaaH** [comment]
How are you certain it's from load to the Heroku app? can you post the logs?

**Comment by deven96** [comment]
You're a collaborator na... look at the logs yourselfSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Mmadu Manasseh <notifications@github.com> Date: 21/03/2020  11:41 am  (GMT+01:00) To: bisoncorps/gophie <gophie@noreply.github.com> Cc: Diretnan Domnan <diretnandomnan@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bisoncorps/gophie] Hosted Gophie keeps crashing (#17) 
How are you certain it's from load to the Heroku app? can you post the logs?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bisoncorps/gophie/issues/17#issuecomment-602025357",
"url": "https://github.com/bisoncorps/gophie/issues/17#issuecomment-602025357",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by deven96** [comment]
You're a collaborator now... take a look at it yourself 
There was no internal error... the dyno just seemed to fail.... first time I'm seeing that happen too but it happened like two or three times in the span of the 7 hours I was using it

**Comment by Tiemma** [comment]
I'd look into this one today 

It should be quite some work

**Comment by deven96** [comment]
Awesome @Tiemma . Although I've not been able to replicate, those weird crashes have been recurrent from time to time so I was still thinking about having multiple hosted mirrors

**Comment by deven96** [comment]
Turns out the crash was due to a request context bug in the code but this feature is still very necessary for load balancing.
