### ISSUE TITLE
Add series downloads

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie#20]
Add series only engines. Open to suggestions on the sites to use

**Comment by MeNsaaH** [comment]
To do this the person must explicitly pass a `--series` argument to tell the engine to compile the series download links

**Comment by deven96** [comment]
Or we could just make explicit series subcommands with dedicated engines. Like https://tvshows.club is a nicely organized one. All the current engines we have now have their series scattered in between the movies but this one is worth checking out

**Comment by MeNsaaH** [comment]
What if the person wants to stream the series?

**Comment by deven96** [comment]
Hmmm.... depends on our definition of stream
Does the person want to binge (we can add multiple links vlc playlist after each other). I think the person would have to specify --binge or --single. Doesn't have to be exact but something like that

**Comment by MeNsaaH** [comment]
That's not what I mean. What I'm saying is how do you define the stream command for a series if we split it into a different subcommand and not a parameter
