### ISSUE TITLE
Movie extension

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie#21]
Return the extension type of the movie e.g mp4, mkv

**Comment by MeNsaaH** [comment]
Return the extension type? What's this for? I can always be extracted from the url

**Comment by deven96** [comment]
Cuz of the mobile. The expo FileSystem doesn't extract it (you have to give filename to save to e.g movie.mp4) and I don't want to keep an extra layer of querying the link just to get the extension

**Comment by MeNsaaH** [comment]
You could write a function that does that. `getMIMEType` or `getExtension` and pass the url to it

**Comment by deven96** [comment]
I was thinking speed wise for doing it on mobile but come to think of it, if we have to get mimetypes of all movies on the scraper end before returning then it'd slow down the entire process a bit more. I'll just do it on the mobile end.
