### ISSUE TITLE
Integrating selenium for javascript based sites

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie#23]
Sites like tfpdl might need selenium to scrape. We could run selenium in conjunction with colly
https://github.com/tebeka/selenium

**Comment by MeNsaaH** [comment]
Sounds interesting.

**Comment by deven96** [comment]
This will however increase the complexity of the user installation process

**Comment by MeNsaaH** [comment]
How? We will add an install script that does everything from downloading to adding to path

**Comment by deven96** [comment]
> How? We will add an install script that does everything from downloading to adding to path

Yeah but then it will have to be cross platform which is another layer of complexity handled by goreleaser up until now
