### ISSUE TITLE
Prompt UI not showing output for coolmoviez

### ISSUE THREAD

**Issue by deven96** [Go-phie/gophie#31]
I was able to log even the titles just before prompt.Run() but still nothing shows up on the screen

**Comment by MeNsaaH** [comment]
Output for UI like list for selection you mean?

**Comment by deven96** [comment]
Yeah... like nothing is visibly showing
But if you hit down button once and click enter, it will download the second movie, and so on

**Comment by MeNsaaH** [comment]
Oh wow, I'll check it out

Manasseh Mmadu

**Comment by MeNsaaH** [comment]
Still persisting?

**Comment by deven96** [comment]
Yep thought I figured it out but nah

> Still persisting?
