### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by Hikaon** [Go-phie/gophie#32]
Logs:

> go get github.com/go-phie/gophie
> # github.com/go-phie/gophie/downloader
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:18:37: undefined: downloader.Data
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:29:13: undefined: downloader.URL
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:34:24: undefined: downloader.Stream
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:45:11: undefined: downloader.Data
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:72:10: undefined: downloader.Data
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:93:2: undefined: config.OutputPath
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:100:9: undefined: downloader.Download
> ../../go/src/github.com/go-phie/gophie/downloader/downloader.go:100:42: undefined: config.ChunkSizeMB
> 

OS: Macos Mojave, Go version go1.14.6 darwin/amd64

**Comment by MeNsaaH** [comment]
Can you try this instead 
```bash 
go get -u github.com/go-phie/gophie
```

**Comment by MeNsaaH** [comment]
@deven96 this has been reproduced. It's also failing, on my end. Need to fix Downloader Package

**Comment by MeNsaaH** [comment]
I turns out the bug is coming from `annie` downloader. A couple of changes have been made and need to be addressed.
